# Generated by Django 4.0.3 on 2022-03-16 20:13

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(max_length=128)),
                ('userName', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
                ('streetAddress', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('suburb', models.CharField(max_length=64)),
                ('postalCode', models.IntegerField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('password', models.CharField(max_length=128)),
                ('bio', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=64)),
                ('lastName', models.CharField(max_length=64)),
                ('userName', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
                ('streetAddress', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('suburb', models.CharField(max_length=64)),
                ('postalCode', models.IntegerField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('password', models.CharField(max_length=128)),
                ('bio', models.CharField(max_length=1024)),
            ],
        ),
    ]
