# Generated by Django 4.0.3 on 2022-03-16 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flickboutique', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='email',
        ),
        migrations.RemoveField(
            model_name='business',
            name='password',
        ),
        migrations.RemoveField(
            model_name='business',
            name='userName',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='userName',
        ),
    ]
