# Generated by Django 4.0.3 on 2022-03-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickboutique', '0010_alter_product_productprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productRating',
            field=models.IntegerField(null=True),
        ),
    ]
