# Generated by Django 4.0.3 on 2022-03-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickboutique', '0012_alter_product_productmanufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productImage',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
