# Generated by Django 4.0.3 on 2022-03-17 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flickboutique', '0016_product_producttotalratings_product_producturl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accentColor', models.CharField(default='#000000', max_length=20)),
                ('backgroundColor', models.CharField(default='#FFFFFF', max_length=20)),
                ('textColor', models.CharField(default='#000000', max_length=20)),
                ('secondaryTextColor', models.CharField(default='#000000', max_length=20)),
                ('productCardColor', models.CharField(default='#FFFFFF', max_length=20)),
                ('productCardGlowColor1', models.CharField(default='orange', max_length=20)),
                ('productCardGlowColor2', models.CharField(default='lightblue', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='colorScheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_color_scheme', to='flickboutique.colorscheme'),
        ),
    ]
