# Generated by Django 4.0.3 on 2022-03-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickboutique', '0019_colorscheme_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productRatingsSum',
            field=models.IntegerField(null=True),
        ),
    ]
