# Generated by Django 4.0.3 on 2022-03-20 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flickboutique', '0020_product_productratingssum'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productRaters',
            field=models.ManyToManyField(related_name='product_raters', to=settings.AUTH_USER_MODEL),
        ),
    ]
