# Generated by Django 4.0.3 on 2022-03-20 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flickboutique', '0022_alter_product_productraters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productRaters',
            field=models.ManyToManyField(related_name='product_raters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentBody', models.TextField(blank=True, null=True)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_commenter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='productComments',
            field=models.ManyToManyField(related_name='product_comments', to='flickboutique.productcomment'),
        ),
    ]
