# Generated by Django 4.0.3 on 2022-03-20 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flickboutique', '0023_alter_product_productraters_productcomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_replier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProductCommentReplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentBody', models.TextField(blank=True, null=True)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_commenter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='productcomment',
            name='replies',
            field=models.ManyToManyField(related_name='product_replies', to='flickboutique.productcommentreplies'),
        ),
    ]
