# Generated by Django 4.0.3 on 2022-03-20 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flickboutique', '0024_alter_productcomment_commenter_productcommentreplies_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcommentreplies',
            old_name='commentBody',
            new_name='replyBody',
        ),
        migrations.RemoveField(
            model_name='productcommentreplies',
            name='commenter',
        ),
        migrations.AddField(
            model_name='productcommentreplies',
            name='replier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_replier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_commenter', to=settings.AUTH_USER_MODEL),
        ),
    ]
