# Generated by Django 4.0.3 on 2022-03-16 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flickboutique', '0002_remove_business_email_remove_business_password_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Business',
            new_name='BusinessInfo',
        ),
        migrations.RenameModel(
            old_name='Customer',
            new_name='CustomerInfo',
        ),
    ]
