# Generated by Django 4.0.3 on 2022-03-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickboutique', '0004_customerinfo_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='userName',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='userName',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
