# Generated by Django 4.0.3 on 2022-03-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickboutique', '0015_product_soldby'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productTotalRatings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='productURL',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='productRating',
            field=models.FloatField(default=0),
        ),
    ]
