# Generated by Django 4.0.3 on 2022-03-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickboutique', '0017_colorscheme_businessinfo_colorscheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorscheme',
            name='schemeName',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
