# Generated by Django 4.0.3 on 2022-03-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickboutique', '0018_colorscheme_schemename'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorscheme',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
