# Generated by Django 4.0.3 on 2022-03-20 17:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flickboutique', '0025_rename_commentbody_productcommentreplies_replybody_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCommentReplies',
            new_name='ProductCommentReply',
        ),
    ]
