# Generated by Django 4.0.3 on 2022-03-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickboutique', '0026_rename_productcommentreplies_productcommentreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='profilePicture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
