# Generated by Django 4.0.3 on 2022-03-26 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flickboutique', '0027_businessinfo_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='colorScheme',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='business_color_scheme', to='flickboutique.colorscheme'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='profilePicture',
            field=models.ImageField(default='noPP.svg', upload_to=''),
        ),
    ]
