# Generated by Django 4.0.3 on 2022-03-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickboutique', '0028_alter_businessinfo_colorscheme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorscheme',
            name='logo',
            field=models.ImageField(default='billbao_logo.png', upload_to=''),
        ),
    ]
