# Generated by Django 4.0.3 on 2022-03-26 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flickboutique', '0029_alter_colorscheme_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='soldBy',
        ),
    ]
