# Generated by Django 4.0.3 on 2022-03-26 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flickboutique', '0032_product_soldby'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(related_name='shopping_cart_items', to='flickboutique.product')),
            ],
        ),
    ]
