# Generated by Django 4.0.3 on 2022-03-27 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flickboutique', '0033_customershoppingcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='flickboutique.product')),
            ],
        ),
        migrations.AlterField(
            model_name='customershoppingcart',
            name='items',
            field=models.ManyToManyField(related_name='shopping_cart_items', to='flickboutique.cartitem'),
        ),
    ]
