# Generated by Django 4.0.3 on 2022-03-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickboutique', '0034_cartitem_alter_customershoppingcart_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customershoppingcart',
            name='items',
            field=models.ManyToManyField(related_name='shopping_cart_items', to='flickboutique.product'),
        ),
    ]
