# Generated by Django 4.0.3 on 2022-03-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickboutique', '0037_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customershoppingcart',
            name='items',
            field=models.ManyToManyField(related_name='shopping_cart_items', to='flickboutique.cartitem'),
        ),
    ]
