# Generated by Django 4.0.3 on 2022-03-28 05:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flickboutique', '0041_businessinfo_profilebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='raters',
            field=models.ManyToManyField(related_name='business_raters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='ratingsSum',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='totalRatings',
            field=models.IntegerField(default=0),
        ),
    ]
